version: '3.8'
services:
  samsaga:
    container_name: samsaga
    image: samsaga
    volumes:
      - ./config:/app/config
      - ./utils:/app/utils
      - ./main.py:/app/main.py
    command: tail -f /dev/null
