version: '3.8'
services:
  sagamma:
    container_name: sagamma
    image: sagamma
    build: ./
    environment:
      - EMAIL=${email}
    volumes:
      - ./config/config.yml:/app/config/config.yml
      - ./results:/app/results
    command: python3 main.py ${args}

  sagamma_jupyter:
    container_name: sagamma_jupyter_${port}
    image: sagamma
    environment:
      - EMAIL=${email}
    ports:
      - ${port}:8888
    volumes:
      - ./results:/app/results
      - ./config/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py
    command: jupyter notebook
