version: '3.8'
services:
  samsaga:
    container_name: samsaga
    image: samsaga
    build: ./
    environment:
      - EMAIL=${email}
    volumes:
      - ./config/config.yml:/app/config/config.yml
      - ./results:/app/results
    command: python3 main.py ${args}

  samsaga_jupyter:
    container_name: samsaga_jupyter_${port}
    image: samsaga
    environment:
      - EMAIL=${email}
    ports:
      - ${port}:8888
    volumes:
      - ./results:/app/results
      - ./config/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py
    command: jupyter notebook
